application: mol-lab
version: points
runtime: python
api_version: 1

builtins:
- datastore_admin: on
- appstats: on
- remote_api: on

inbound_services:
- channel_presence

handlers:

- url: /frontend/points(/.*)?
  script: frontend.py
  login: admin

- url: /backend/harvest(/.*)?
  script: harvest.py

- url: /backend/tile(/.*)?
  script: tile.py

- url: /backend/render(/.*)?
  script: render.py

- url: /_ah/channel/connected/.*
  script: points.py

- url: /_ah/channel/disconnected/.*
  script: points.py
    
- url: /js
  static_dir: js
