# This section provides information about the source, such as name and contact
# information.
# 
Source:
  name: Jetz Lab 
  email: walter.jetz@yale.edu

# This section provides information about all collections provided by the 
# source.
# 
Collections:
  
# This section contains information about a single collection.
# 

# Required directory name of the collection.
# 
- Collection: birds
   
  # Required MOL metadata (http://www.google.com/fusiontables/DataSource?dsrcid=1348212)
  #  
  Fields:
    Required: 
      areaid: 1
      polygonid: 1
      identifier: 1
      bibliographiccitation: =CITATION
      collectionid: "Jetz Bird Range Maps"
      contact: "Walter Jetz <walter.jetz@yale.edu>"
      creator: Jetz Lab
      type: "expert opinion range map"
      dateSubmitted: 2011
      rights: Creative Commons Attribution-Share Alike 3.0 Unported license. http://creativecommons.org/licenses/by-sa/3.0/deed.en
      scientificname: =Latin
      title: Jetz Bird Range Maps
      verbatimsrs: +proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +a=6378137 +b=6378137 +units=m +no_defs

    # Optional MoL metadata (http://www.google.com/fusiontables/DataSource?dsrcid=1348212)
    #
    Optional:
      abundance: =ABUNDANCE
      basemaps:
      vernacularname:
      coverage: Global
      description: Improved bird range maps.
      language: en
      publisher:  Jetz Lab
