# This section provides information about the source, such as name and contact
# information.
# 
Source:
  name: GBIF (Tim Robertson)
  email: Tim Robertson <timrobertson100@gmail.com>

# This section provides information about all collections provided by the 
# source.
# 
Collections:
  
# This section contains information about a single collection.
# 

# Required directory name of the collection.
# 
- Collection: mol.txt
   
  Fields:

    # Required MoL DBF fields 
    # http://www.google.com/fusiontables/DataSource?dsrcid=1348212
    #
    Required:
      areaid: 1
      polygonid: 1
      identifier: 
        - "OccurenceId"
        # Or should this be 'CatalogueNumber'?
      bibliographiccitation: "GBIF data dump"
      collectionid: 
        - "CollectionCode"
      contact: "Tim Robertson <timrobertson100@gmail.com>"
      creator: "Global Biodiversity Information Facility"
      type: "points"
      dateSubmitted: "2012-01-28"
      rights: "Unknown"
      scientificName: 
        - "ScientificName"
      title: "GBIF data dump"
      verbatimsrs: "+proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +a=6378137 +b=6378137 +units=m +no_defs"

    # Optional MoL DBF fields
    # http://www.google.com/fusiontables/DataSource?dsrcid=1348212
    #
    Optional:
      AreaName: 
        - Country
      SurveyStartDate: 
        - "EventDate"
        - "Year"
      SurveyEndDate: 
        - "EventDate"
        - "Year"
      Contributor: "Gaurav Vaidya <gaurav@ggvaidya.com>"
      TaxonID:
        - "TaxonId" 
