# This section provides information about the source, such as name and contact
# information.
# 
Source:
  name: IUCN
  email: redlist@iucn.org

# This section provides information about all collections provided by the 
# source.
# 
Collections:
  
# This section contains information about a single collection.
# 

# Required directory name of the collection.
# 
- Collection: mammals
   
  Fields:

    # Required MoL DBF fields 
    # http://www.google.com/fusiontables/DataSource?dsrcid=1348212
    #
    Required:
      areaid: 1
      polygonid: 1
      identifier: 1
      bibliographiccitation: "IUCN 2009. IUCN Red List of Threatened Species. Version 2009.1. http://www.iucnredlist.org"
        # What about =CITATION?
      collectionid: "IUCN Red List version AAAA" 
      contact: "Vineet Katariya <Vineet.Katariya@iucn.org>"
      creator: =COMPILER
      type: "expert opinion range map"
      dateSubmitted: "2011"
      rights: "Creative Commons® Attribution-Share Alike 3.0 Unported license. http://creativecommons.org/licenses/by-sa/3.0/deed.en"
      rights: "Creative Commons® Attribution-Share Alike 3.0 Unported license. http://creativecommons.org/licenses/by-sa/3.0/deed.en"
      scientificname: =BINOMIAL
      title: "IUCN Red List™ of Threatened Species"
      verbatimsrs: "+proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +a=6378137 +b=6378137 +units=m +no_defs"

    # Optional MoL DBF fields
    # http://www.google.com/fusiontables/DataSource?dsrcid=1348212
    #
    Optional:
      basemaps:  
      vernacularName:      
      coverage: Global
      description: |
          This dataset contains distribution information of species assessed for 
          The IUCN Red List of Threatened Species. The maps are developed as part 
          of a comprehensive assessment of global in order to highlight taxa 
          threatened with extinction, and thereby promote their conservation.
      distributioncomment: =DIST_COMM     
      establishmentmeans: =ORIGIN 
      occurrencestatus: =PRESENCE  
      polygonname: =ISLAND
      seasonality: =SEASONAL
      surveystartdate: =YEAR
      surveyenddate: =YEAR
      taxonremarks: 
      visible: true

- Collection: amphibians

  Fields:

    # Required MoL DBF fields 
    # http://www.google.com/fusiontables/DataSource?dsrcid=1348212
    #
    Required:
      areaid: 1
      polygonid: 1
      identifier: =ID_NO
      bibliographiccitation: "IUCN 2009. IUCN Red List of Threatened Species. Version 2009.1. http://www.iucnredlist.org"
        # What about =CITATION?
      collectionid: "IUCN Red List™ version AAAA" 
      contact: "Vineet Katariya <Vineet.Katariya@iucn.org>"
      creator: =COMPILER
      type: "expert opinion range map"
      dateSubmitted: "2011"
      rights: "Creative Commons Attribution-Share Alike 3.0 Unported license. http://creativecommons.org/licenses/by-sa/3.0/deed.en"
      scientificname: =BINOMIAL
      title: "IUCN Red List™ of Threatened Species"
      verbatimsrs: "+proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +a=6378137 +b=6378137 +units=m +no_defs"

    # Optional MoL DBF fields
    # http://www.google.com/fusiontables/DataSource?dsrcid=1348212
    #
    Optional:
      basemaps:  
      vernacularName:      
      coverage: Global
      description: |
          This dataset contains distribution information of species assessed for 
          The IUCN Red List™ of Threatened Species. The maps are developed as part 
          of a comprehensive assessment of global in order to highlight taxa 
          threatened with extinction, and thereby promote their conservation.
      distributioncomment: =DIST_COMM     
      establishmentmeans: =ORIGIN 
      occurrencestatus: =PRESENCE  
      polygonname: =ISLAND
      seasonality: =SEASONAL
      surveystartdate: =YEAR_
      surveyenddate: =YEAR_
      taxonremarks: =TAX_COMMEN
      visible: true
