# This section provides information about the source, such as name and contact
# information.
# 
Source:
  name: "APIS - Antarctic Pack Ice Seals 1994-1999, plus historical data from the 1980s"
  url: 
    - "http://data.aad.gov.au/aadc/metadata/metadata_redirect.cfm?md=AMD/AU/APIS"
    - http://data.gbif.org/datasets/resource/83
  email: metadata at aad.gov.au

# This section provides information about all collections provided by the 
# source.
# 
Collections:
  
# This section contains information about a single collection.
# 

# Required directory name of the collection.
# 
- Collection: apis.csv
   
  Fields:

    # Required MoL DBF fields 
    # http://www.google.com/fusiontables/DataSource?dsrcid=1348212
    #
    Required:
      areaid: 1
      polygonid: 1
      identifier: =Identifier
      bibliographiccitation: "APIS - Antarctic Pack Ice Seals 1994-1999, plus historical data from the 1980's, published by the Australian Antarctic Data Centre (accessed through GBIF data portal, APIS - Antarctic Pack Ice Seals 1994-1999, plus historical data from the 1980's, http://data.gbif.org/datasets/resource/83)"
      collectionid: "=Collection Code"
      contact: "Colin Southwell <colin.southwell at aad.gov.au>"
      creator: "Australian Antarctic Data Centre, Australia"
      type: "pointoccurrence"
      dateSubmitted: "2011-12-22"
      rights: "Creative Commons® Attribution 3.0 Unported license. http://creativecommons.org/licenses/by/3.0/"
      scientificname: "=Scientific name"
      title: "APIS - Antarctic Pack Ice Seals 1994-1999, plus historical data from the 1980's"
      verbatimsrs: "+proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +a=6378137 +b=6378137 +units=m +no_defs"

    # Optional MoL DBF fields
    # http://www.google.com/fusiontables/DataSource?dsrcid=1348212
    #
    Optional:
      # TODO: Add more of that metadata in.
      visible: true
